name: Build and test

on:
  push:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        
    steps:
    - uses: actions/checkout@v3

    - name: Set reusable strings
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

    - name: Configure CMake
      run: cmake -B ${{ steps.strings.outputs.build-output-dir }} -S ${{ github.workspace }} -DENABLE_TEST=ON

    - name: Build
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }}

    - name: Unit tests
      run: ctest --test-dir ${{ steps.strings.outputs.build-output-dir }}
      